### ISSUE TITLE
Incompatible with the latest release of Epic Fight

### ISSUE THREAD

**Issue by LoSilopante** [pitbox46/epicfightnbt#3]
Epic Fight got a small patch to fix an incompatibility with GeckoLib and now EpicFightNBT crashes the game when creating its config file during world gen.

- Lines [8 and 9](https://github.com/pitbox46/epicfightnbt/blob/64eb5a450081d753f16dcc975e3176fc9b74e014/src/main/java/github/pitbox46/epicfightnbt/Config.java#L7-L8) are:

```
import maninhouse.epicfight.capabilities.item.*;
import maninhouse.epicfight.config.CapabilityConfig;
```
- should be updated to:

```
import yesman.epicfight.capabilities.item.*;
import yesman.epicfight.config.CapabilityConfig;
```

- Mention [EpicFight#629](https://github.com/Yesssssman/epicfightmod/issues/629#issue-1022751350)

**Comment by pitbox46** [comment]
Fixed in newest version
