### ISSUE TITLE
Suggestion: add Tetra shields to be intigrated

### ISSUE THREAD

**Issue by Shibva** [pitbox46/epicfightnbt#4]
I made a preort recently and found out that the new version that is relased now has a shield tag for shields, meaning its possable now to assin tetra shields can be applied using this mod

can you do this please?

**Comment by pitbox46** [comment]
I will look into it

**Comment by SteamDoge9000** [comment]
acutaly no need to
![image](https://user-images.githubusercontent.com/38770780/139771932-ac904198-8907-4f63-9786-497c02972ef6.png)

**Comment by Shibva** [comment]
i linked your mod to the original dev for Epic fight for refrence and idk if they used some of it or something

seems like what he did automaticaly did that for all shields

**Comment by Shibva** [comment]
though I wonder if that might not be the case if they decide to add shield abilities,

**Comment by Shibva** [comment]
wait nvm
forget I said anything, I was nto in combat mode for that shot XD

**Comment by Shibva** [comment]
is the integration complete?

**Comment by pitbox46** [comment]
I suppose not. You confused me with your comments, so I thought this was a non-issue. I will look into it now though

**Comment by Shibva** [comment]
yeah, sorry about that 😅

**Comment by pitbox46** [comment]
Added shield and trident support in latest commit. Will push an update to Curseforge tonight.

**Comment by Shibva** [comment]
is it me or is it not properly doing the animation like it did before
![image](https://user-images.githubusercontent.com/38770780/141237796-c45af0ff-191b-400c-86d2-b03c1d4c8e7c.png)

**Comment by Shibva** [comment]
I thought that in intigrating this that the shields would now properly render like the other shields

**Comment by pitbox46** [comment]
The latest release also has a change with the config directory. 

> CONFIG SYSTEM CHANGED IN 1.3.0
In order to fix your configs, rename them to `epicfightnbt.json` and place it under the folder named `serverconfig`

Otherwise, I don't have a clue about what's going on since it is now registered like every other weapon type.

**Comment by Shibva** [comment]
![image](https://user-images.githubusercontent.com/38770780/141267373-410eab85-b51d-4897-bcd7-79710a622eb1.png)
idk, I was expecting it todo this with the other shields, I guess ill have to bring it up on the main mod issue pannel
